### ISSUE TITLE
Additional Backends

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#11]
_From @benyanke on April 19, 2018 1:21_

This thread is for requests of additional backends.

MySQL seems the first obvious one. Feel free to chime in if anyone has other ideas. I'll implement as I'm able or accept PRs.

Currently tracked backends:
 * MySQL
 * Postgres
 * CockroachDB (would likely be the same as postgres)
 * Etcd
 * Amazon Cognito REST API

Before implementing these backends, perhaps it would be useful to add an interface layer to cleanly specify the contract between a backend provider and glauth, and also move backend providers into their own directory.

**Comment by jimmonteath** [comment]
An Amazon Cognito REST API backend would be very useful for apps that do user authorization through LDAP bind and/or fetch user attributes.

**Comment by benyanke** [comment]
@jimmonteath That would be rather interesting! I can't say it's highest on my list, but I would certainly accept a well-written PR implementing it as a backend. If possible, I'd like it to also have integration tests as well, which can run in CI.

**Comment by n1trux** [comment]
PostgreSQL would be cool, too.

**Comment by benyanke** [comment]
Absolutely - I'd imagine the implementation would be 95% shared with MySQL.

**Comment by jcgruenhage** [comment]
A few more things that would be neat:
 - CockroachDB (distributed SQL database)
 - etcd (distributed key value storage)

I think it would make sense to edit the first post here with a list of proposed things, to have a cleaner overview than reading the whole issue, maybe even structured into SQL, KV, File, REST or something like that.

**Comment by Slach** [comment]
https://github.com/summerwind/etcdap
LDAP with etcd backend experimental implementation

etcd will really interested for me

**Comment by StephanMeijer** [comment]
I need postgres support.

**Comment by fillup** [comment]
I'd love to run this in front of an existing REST API authentication service I have to also provide an LDAP interface for a couple services that don't support anything else. So most useful for me would be an interface I can use to implement a custom backend. Or perhaps some generic HTTPS backend with a common API expectation would work too.

**Comment by hongkongkiwi** [comment]
Very keen on mongodb

**Comment by p3lim** [comment]
Throwing [Vault](https://www.vaultproject.io/) into the pool.

**Comment by poVoq** [comment]
Given that there is now experimental Owncloud support, it would be really cool if Nextcloud was also included. Not sure how far the codebase has diverged in that particular aspect from Owncloud.

**Comment by butonic** [comment]
poVoq: the oc/nc provisioning api should still be the same as it is based on ocs. However, querying all users is inefficient because you have to first get the list of userids and then fetch the user info one by one. Which is why we are looking at building an [owncloud app that provides a graphapi](https://github.com/owncloud/graphapi) endpoint. If that app runs as an nc app I cannot say. I doubt it. Maybe [caching](https://github.com/glauth/glauth/issues/61) the provisioning api is good enough. PR welcome.

Anyway, I moved the backends into their own package, so that part of this issue is done.

Also, the backend Handler interface currently asks for `Bind()`, `Search()` and `Close()` functions expected by the actual ldap server implementation we are wrapping:
```
// interface for backend handler
type Backend interface {
	ldap.Binder
	ldap.Searcher
	ldap.Closer
}
```
That interface could be made more concrete, however I like the handler style of the contract ... opne a new issue if you have an idea how we might improve the interface.

To prevent this issue from becoming a never ending story I'll close it now. Please open new issues for dedicated backends. Then we can discuss how to solve them individually. I'll happily review and merge PRs. I'll also add a `backend-request` label so we can keep track of the list.

**Comment by butonic** [comment]
Ok, I created issues for all mentioned backends: https://github.com/glauth/glauth/issues?q=is%3Aissue+is%3Aopen+label%3Abackend-request

PRs welcome!
