### ISSUE TITLE
postgres backend

### ISSUE THREAD

**Issue by butonic** [glauth/glauth#118]
fixed by https://github.com/glauth/glauth/pull/94

**Comment by shah** [comment]
This is a great project! @butonic is PostgreSQL support now in the GLAuth released version? It seemed to me that #94 was closed but the code has not been merged in yet? My use case was the following: using GLAuth as LDAP front end to a GitLab-based PosgreSQL database so that I can use GitLab authentication as backend and GLAuth as front end. Is this possible?

**Comment by sc0rp10** [comment]
hi! Is there any progress with this task?

**Comment by Fusion** [comment]
It is currently checked in the dev branch. Until a new release comes out you will have to build glauth yourself.
