### ISSUE TITLE
directions on what is required to join a windows computer to the domain

### ISSUE THREAD

**Issue by aae42** [glauth/glauth#148]
it would be amazing to know what all would be required for DNS and etc to join a windows computer to a glauth domain...

not just as a lightweight replacement for microsoft's domain services, but this would be incredibly useful as an integration testing tool for windows-based configuration management tools that rely on some simple AD services that could be mocked with glauth

**Comment by butonic** [comment]
True, but AFAICT currently way out of scope for glauth. It has more to do with kerberos. A good first point might be https://ldapwiki.com/wiki/Join%20AD%20Domain and discover the relevant LDAP attributes from there.

Better yet might be https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller because you can use samba to set up a domain controller. Or look for a docker container that you can use for integration testing.

I'll close this for now but feel free to flesh out the idea here. We can always reopen if someone wants to actively work on this.
