### ISSUE TITLE
Invalid AWS region: ap-south-1

### ISSUE THREAD

**Issue by pratikbalar** [glauth/glauth#182]
Version: `v1.1.2`

```bash
$ glauth -c s3://my-bucket/config.cfg -K xxxx -S xxxx -r ap-south-1

14:06:31.712779 main ▶ CRIT 001 Configuration file error: Invalid AWS region: ap-south-1
```
Credentials and region are fine, I quadruple checked that.

When i tried with `us-east-1`
```bash
glauth -c s3://my-bucket/config.cfg -K xxxx -S xxxx -r us-east-1 
14:11:49.516015 main ▶ CRIT 001 Configuration file error: Get https://s3.amazonaws.com/my-bucket/config.cfg: 301 response missing Location header
```

**Comment by Fusion** [comment]
Hi @pratikbalar I have some good news: I tried to reproduce this issue and could not. I created and tested against a bucket in ap-west-1, one in ap-east-1 and one in ap-south-1.

I think what you have been seeing is due to GLAuth needing a new release! The issue likely is that the public versions are linked against an outdated version of the S3 SDK:

- ap-east-1 would not work well due to the older SDK not connecting to the proper region and not understanding the hint returned by the endpoint
- ap-south-1 would not work at all because the Mumbai region did not exist at the time and has since been added

With the coming V2, this all seems to work well.
