### ISSUE TITLE
standard for the released artefacts?

### ISSUE THREAD

**Issue by bodsch** [glauth/glauth#292]
Is it possible to establish a standard for the artefacts?

Zip archives are offered for download for [2.1.0](https://github.com/glauth/glauth/releases/tag/v2.1.0)

For [2.2.0-RC](https://github.com/glauth/glauth/releases/tag/v2.2.0-RC1) only the binaries.

It will be difficult to get a meaningful automation here. :)

**Comment by Fusion** [comment]
You are making a good point. These wild changes are due to the fact that there was not unified way of building for all the targets at the same time, while providing multi-platform containers as well.

I think I have finally cracked multiple target builds when using plugins (hint: never use plugins unless you don't have to! Go does not like plugins)

Anyway, with plugins now living in their own repositories, I think the format is now stable.  Sorry for the inconvenience.

**Comment by bodsch** [comment]
All good.

I know the on-the-fly developer cycle myself.
In the meantime I found a solution, but it consumes ratelimits at github.

Will the current format (a single exec file) be maintained?
Will the plugins also be offered compiled in the future? (I cannot assume a build environment on the target systems).

**Comment by Fusion** [comment]
Yes. 

Here is the new (current) format. Seems like a good idea to document it, indeed.
 
The idea is that plugins are optional, and thus they now have their own projects. Therefore, to download v2.2.0RC1 with its current plugins, you would retrieve the binaries from:

- GLAuth core: https://github.com/glauth/glauth/releases/tag/v2.2.0-RC1
- Postgres plugin: https://github.com/glauth/glauth-postgres/releases/tag/v2.2.0-RC1
- MySQL plugin: https://github.com/glauth/glauth-mysql/releases/tag/v2.2.0-RC1
- SQLite plugin: https://github.com/glauth/glauth-sqlite/releases/tag/v2.2.0-RC1

Additional plugins can be retrieved from their own repositories.

**Comment by bodsch** [comment]
> @Fusion Great! Perhaps this issue can be closed now?

From my side, the issue can be closed.
