### ISSUE TITLE
Refactor Makefile 

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#40]
Currently in the build section there's a lot of duplication. This could be easily parameterized.

**Comment by Fusion** [comment]
I think you are too hard on the poor Makefile :)

Right now, it looks pretty clean to me. Yes, there is some duplication but it makes it easier to figure out what platform you are building for. Due to the number of permutations that exist when writing plugins, I made the plugins/ Makefile dependent on environment variables. I don't think it's all that great.
