### ISSUE TITLE
trying to use glauth to make a corporate directory for poly vvx 450 IP phones

### ISSUE THREAD

**Issue by jburg379** [glauth/glauth#441]
I have the glauth service running and when I use ldapsearch on the server the users I created come up. Since we have a small set up I am using datastore = "config". I enabled corporate directory on the poly phone and I am able to log in. However, nothing shows up on the directory and when I try to search nothing shows up. The journal shows (&(objectClass=*)(givenName>=Ryan)(givenName<=zz)(givenName=Ryan*)(extension=110)) when I try to used advanced search. My manager and I have tried editing the poly phone config files several times but we can't seem to get anything to work. 

Could anyone tell me what we could be missing?

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the GLAuth configuration to include necessary object classes and attributes for Poly phone directory search compatibility. Add givenName and sn attributes to user entries, and include inetOrgPerson objectClass.

You can review changes in this commit: https://github.com/lattaai11/glauth-glauth-441/commit/6036509a908d11b10a4a22d1a33d71a08072f35f.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the config handler to properly handle givenName and extension attributes in LDAP searches. This will allow the Poly phone to retrieve and display directory information correctly.

You can review changes in this commit: https://github.com/lattaai11/glauth-glauth-441/commit/87278934bd79ac55670da3d4ce6246434603957b.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jburg379** [comment]
I figured it out
